apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gamego-api
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName: spring-gamego-api-service
          servicePort: 80
