apiVersion: v1
kind: Service
metadata:
  name: spring-gamego-frontend-service 
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000 
  selector:
    name: spring-gamego-frontend
